<!DOCTYPE html>
<html>
<head>
    <title>FISCHER ||| https://fischer.web1.dtweb.cz/</title>
    <meta name="generator" content="HTMLTestRunner 1.0.17"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" href="stylesheet.css">
    <script src="script.js"></script>
    <style>
        
    </style>
    <script>
        
    </script>
</head>
<body>
<div class='heading'>
    <h1 style="margin-left:1ex;">FISCHER ||| https://fischer.web1.dtweb.cz/</h1>
    
    <p class='attribute'><strong>Start Time : </strong> 2023-09-20 14:40:43</p>
    
    <p class='attribute'><strong>Duration : </strong> 0:02:43.335956</p>
    
    <p class='attribute'><strong>Status : </strong> Pass 2 Error 38</p>
    
    <p class='attribute'><strong>Descrition : </strong> FISCHER WEB Suite Report Version : atcom online sputestni</p>
    
    <p class='attribute'><strong>Tested By : </strong> Unknown</p>
    
</div>
<div>
    <p id='show_detail_line'><b>Show</b>
        <button><a href='javascript:showCase(0)' style="color:#660066;">Summary</a></button>
        <button><a href='javascript:showCase(1)' style="color:#660066;">Failed</a></button>
        <button><a href='javascript:showCase(2)' style="color:#660066;">Passed</a></button>
        <button><a href='javascript:showCase(3)' style="color:#660066;">All</a></button>
    </p>
    <table id='result_table'>
        <colgroup>
            <col align='left'/>
            <col align='right'/>
            <col align='right'/>
            <col align='right'/>
            <col align='right'/>
            <col align='right'/>
        </colgroup>
        <tr id='header_row'>
            <td>Test Group/Test case</td>
            <td>Count</td>
            <td>Pass</td>
            <td>Fail</td>
            <td>Error</td>
            <td>View</td>
        </tr>
        
        <tr class='passClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c1','1')">FW_Automation_Local_Deploy_PyCharm.CovidInfo_D.TestCovidInfo_D</a></td>
            <td>1</td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>
                <button><a href="javascript:showClassDetail('c1','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="pt1.1" class='hiddenRow'>
                <td class='passCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_pt1.1')">test_covidInfo_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_pt1.1')" style="color:#660066;">
                                PASS
                            </a></button>
                        <div id='div_pt1.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_pt1.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre>2023-09-20 14:41:28.114480 : nenasle se exponea banner
2023-09-20 14:41:28.175318 : gridy jdou videt
2023-09-20 14:41:28.184294 : gridy jdou videt
2023-09-20 14:41:28.192272 : gridy jdou videt
2023-09-20 14:41:28.200251 : gridy jdou videt
2023-09-20 14:41:28.210224 : gridy jdou videt
2023-09-20 14:41:28.218203 : gridy jdou videt
2023-09-20 14:41:28.226182 : gridy jdou videt
2023-09-20 14:41:28.235158 : gridy jdou videt
2023-09-20 14:41:28.244134 : gridy jdou videt
2023-09-20 14:41:28.251115 : gridy jdou videt
2023-09-20 14:41:28.260092 : gridy jdou videt
2023-09-20 14:41:28.268071 : gridy jdou videt
2023-09-20 14:41:28.276048 : gridy jdou videt
2023-09-20 14:41:28.284027 : gridy jdou videt
2023-09-20 14:41:28.292006 : gridy jdou videt
2023-09-20 14:41:28.300983 : gridy jdou videt
2023-09-20 14:41:28.309958 : gridy jdou videt
2023-09-20 14:41:28.317937 : gridy jdou videt
2023-09-20 14:41:28.325916 : gridy jdou videt
2023-09-20 14:41:28.335890 : gridy jdou videt
2023-09-20 14:41:28.344865 : gridy jdou videt
2023-09-20 14:41:28.352844 : gridy jdou videt
2023-09-20 14:41:28.362818 : gridy jdou videt
2023-09-20 14:41:28.370796 : gridy jdou videt
2023-09-20 14:41:28.378775 : gridy jdou videt
2023-09-20 14:41:28.386754 : gridy jdou videt
2023-09-20 14:41:28.395729 : gridy jdou videt
2023-09-20 14:41:28.403708 : gridy jdou videt
2023-09-20 14:41:28.411687 : gridy jdou videt
2023-09-20 14:41:28.420663 : gridy jdou videt
2023-09-20 14:41:28.429639 : gridy jdou videt
2023-09-20 14:41:28.437618 : gridy jdou videt
2023-09-20 14:41:28.446593 : gridy jdou videt
2023-09-20 14:41:28.455570 : gridy jdou videt
2023-09-20 14:41:28.464546 : gridy jdou videt
2023-09-20 14:41:28.473522 : gridy jdou videt
2023-09-20 14:41:28.481501 : gridy jdou videt
2023-09-20 14:41:28.490477 : gridy jdou videt
2023-09-20 14:41:28.498456 : gridy jdou videt
2023-09-20 14:41:28.506434 : gridy jdou videt
2023-09-20 14:41:28.515411 : gridy jdou videt
2023-09-20 14:41:28.524386 : gridy jdou videt
2023-09-20 14:41:28.532365 : gridy jdou videt
2023-09-20 14:41:28.541341 : gridy jdou videt
2023-09-20 14:41:28.550318 : gridy jdou videt
2023-09-20 14:41:28.558296 : gridy jdou videt
2023-09-20 14:41:28.566274 : gridy jdou videt
2023-09-20 14:41:28.575251 : gridy jdou videt
2023-09-20 14:41:28.583229 : gridy jdou videt
2023-09-20 14:41:28.592206 : gridy jdou videt
2023-09-20 14:41:28.600184 : gridy jdou videt
2023-09-20 14:41:28.609160 : gridy jdou videt
2023-09-20 14:41:28.618136 : gridy jdou videt
2023-09-20 14:41:28.626115 : gridy jdou videt
2023-09-20 14:41:28.635091 : gridy jdou videt
2023-09-20 14:41:28.689944 : content jdou videt
2023-09-20 14:41:28.697923 : content jdou videt
2023-09-20 14:41:28.706899 : content jdou videt
2023-09-20 14:41:28.715876 : content jdou videt
2023-09-20 14:41:28.723854 : content jdou videt
2023-09-20 14:41:28.732830 : content jdou videt
2023-09-20 14:41:28.741807 : content jdou videt
2023-09-20 14:41:28.750782 : content jdou videt
2023-09-20 14:41:28.758760 : content jdou videt
2023-09-20 14:41:28.768735 : content jdou videt
2023-09-20 14:41:28.776713 : content jdou videt
2023-09-20 14:41:28.785689 : content jdou videt
2023-09-20 14:41:28.793668 : content jdou videt
2023-09-20 14:41:28.803641 : content jdou videt
2023-09-20 14:41:28.812617 : content jdou videt
2023-09-20 14:41:28.820596 : content jdou videt
2023-09-20 14:41:28.830570 : content jdou videt
2023-09-20 14:41:28.839545 : content jdou videt
2023-09-20 14:41:28.847524 : content jdou videt
2023-09-20 14:41:28.856501 : content jdou videt
2023-09-20 14:41:28.866474 : content jdou videt
2023-09-20 14:41:28.875450 : content jdou videt
2023-09-20 14:41:28.884425 : content jdou videt
2023-09-20 14:41:28.893402 : content jdou videt
2023-09-20 14:41:28.902378 : content jdou videt
2023-09-20 14:41:28.911354 : content jdou videt
2023-09-20 14:41:28.919332 : content jdou videt
2023-09-20 14:41:28.929306 : content jdou videt
2023-09-20 14:41:28.938282 : content jdou videt
2023-09-20 14:41:28.947258 : content jdou videt
2023-09-20 14:41:28.957232 : content jdou videt
2023-09-20 14:41:28.965210 : content jdou videt
2023-09-20 14:41:28.974186 : content jdou videt
2023-09-20 14:41:28.984160 : content jdou videt
2023-09-20 14:41:28.993136 : content jdou videt
2023-09-20 14:41:29.003109 : content jdou videt
2023-09-20 14:41:29.012085 : content jdou videt
2023-09-20 14:41:29.022058 : content jdou videt
2023-09-20 14:41:29.031034 : content jdou videt
2023-09-20 14:41:29.040011 : content jdou videt
2023-09-20 14:41:29.050981 : content jdou videt
2023-09-20 14:41:29.059957 : content jdou videt
2023-09-20 14:41:29.068933 : content jdou videt
2023-09-20 14:41:29.079905 : content jdou videt
2023-09-20 14:41:29.088880 : content jdou videt
2023-09-20 14:41:29.097856 : content jdou videt
2023-09-20 14:41:29.106832 : content jdou videt
2023-09-20 14:41:29.116805 : content jdou videt
2023-09-20 14:41:29.126779 : content jdou videt
2023-09-20 14:41:29.135755 : content jdou videt
2023-09-20 14:41:29.145729 : content jdou videt
2023-09-20 14:41:29.154704 : content jdou videt
2023-09-20 14:41:29.163680 : content jdou videt
2023-09-20 14:41:29.173654 : content jdou videt
2023-09-20 14:41:29.183627 : content jdou videt
2023-09-20 14:41:29.187616 : https://fischer.web1.dtweb.cz/covid-info
</pre>
                            <pre style="color: red;"></pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='passClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c2','1')">FW_Automation_Local_Deploy_PyCharm.Detail_D.TestDetailHotelu_D</a></td>
            <td>1</td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>
                <button><a href="javascript:showClassDetail('c2','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="pt2.1" class='hiddenRow'>
                <td class='passCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_pt2.1')">test_detail_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_pt2.1')" style="color:#660066;">
                                PASS
                            </a></button>
                        <div id='div_pt2.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_pt2.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre>2023-09-20 14:41:47.886688 : https://fischer.web1.dtweb.cz//recko/korfu/roda/angela-beach?D=1126|1129|826|1225|1124|1128|623|1059|1118|1119|1121|741|735|618|619|624|1127|973|1125|861|1115|1132|1120|709|711|1117|603|1116|1130|993|1131|595|614|648|972|1123|1093|1198|1114|1122|620|746&DD=2023-08-24&DP=4305&DPR=FISCHER+ATCOM&DS=256&GIATA=632&HID=794&MNN=7&MT=5&NN=7&PID=CFU50152&RD=2023-08-31&TO=4305&df=2023-08-01|2023-09-30&nnm=7|8|9|10|11|12|13&sortby=Departure&tt=1&ttm=1#/prehled
</pre>
                            <pre style="color: red;"></pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c3','5')">FW_Automation_Local_Deploy_PyCharm.Detail_C.TestDetailHotelu_C</a></td>
            <td>5</td>
            <td>0</td>
            <td>0</td>
            <td>5</td>
            <td>
                <button><a href="javascript:showClassDetail('c3','5')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft3.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft3.1')">test_detail_fotka</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft3.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft3.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft3.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\Detail_C.py", line 38, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft3.2" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft3.2')">test_detail_terminy_filtr_meal</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft3.2')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft3.2' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft3.2').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\Detail_C.py", line 38, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft3.3" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft3.3')">test_detail_terminy_filtr_airport</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft3.3')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft3.3' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft3.3').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\Detail_C.py", line 38, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft3.4" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft3.4')">test_detail_price_sorter_terminy_cheap</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft3.4')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft3.4' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft3.4').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\Detail_C.py", line 38, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft3.5" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft3.5')">test_detail_price_sorter_terminy_expensive</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft3.5')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft3.5' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft3.5').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\Detail_C.py", line 38, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c4','1')">FW_Automation_Local_Deploy_PyCharm.DetskeKluby_D.TestDetskeKluby_D</a></td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>1</td>
            <td>
                <button><a href="javascript:showClassDetail('c4','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft4.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft4.1')">test_kluby_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft4.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft4.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft4.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\DetskeKluby_D.py", line 12, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c5','1')">FW_Automation_Local_Deploy_PyCharm.dovolena_D.TestDovolena_D</a></td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>1</td>
            <td>
                <button><a href="javascript:showClassDetail('c5','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft5.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft5.1')">test_dovolena_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft5.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft5.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft5.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\dovolena_D.py", line 13, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c6','1')">FW_Automation_Local_Deploy_PyCharm.FM_D.TestFMexotika_D</a></td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>1</td>
            <td>
                <button><a href="javascript:showClassDetail('c6','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft6.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft6.1')">test_FM_exotika_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft6.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft6.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft6.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\FM_D.py", line 50, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c7','2')">FW_Automation_Local_Deploy_PyCharm.fulltext_C.Test_Fulltext_C</a></td>
            <td>2</td>
            <td>0</td>
            <td>0</td>
            <td>2</td>
            <td>
                <button><a href="javascript:showClassDetail('c7','2')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft7.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft7.1')">test_fulltext_naseptavac</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft7.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft7.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft7.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\fulltext_C.py", line 21, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft7.2" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft7.2')">test_fulltext_results_status_check</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft7.2')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft7.2' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft7.2').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\fulltext_C.py", line 21, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c8','1')">FW_Automation_Local_Deploy_PyCharm.groupsearch_D.Test_Groupsearch_D</a></td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>1</td>
            <td>
                <button><a href="javascript:showClassDetail('c8','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft8.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft8.1')">test_groupsearch_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft8.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft8.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft8.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\groupsearch_D.py", line 67, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c9','1')">FW_Automation_Local_Deploy_PyCharm.HP_D.TestHP_D</a></td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>1</td>
            <td>
                <button><a href="javascript:showClassDetail('c9','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft9.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft9.1')">test_homePage_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft9.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft9.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft9.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\HP_D.py", line 12, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c10','1')">FW_Automation_Local_Deploy_PyCharm.LM_D.TestLM_D</a></td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>1</td>
            <td>
                <button><a href="javascript:showClassDetail('c10','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft10.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft10.1')">test_lM_isDisplayed</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft10.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft10.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft10.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\LM_D.py", line 12, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c11','2')">FW_Automation_Local_Deploy_PyCharm.pobocky.TestPobocky_C</a></td>
            <td>2</td>
            <td>0</td>
            <td>0</td>
            <td>2</td>
            <td>
                <button><a href="javascript:showClassDetail('c11','2')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft11.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft11.1')">test_pobocky_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft11.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft11.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft11.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\pobocky.py", line 39, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft11.2" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft11.2')">test_pobocky_C_click_to_detail_popup_check</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft11.2')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft11.2' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft11.2').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\pobocky.py", line 39, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c12','8')">FW_Automation_Local_Deploy_PyCharm.poznavacky.TestPoznavacky_D</a></td>
            <td>8</td>
            <td>0</td>
            <td>0</td>
            <td>8</td>
            <td>
                <button><a href="javascript:showClassDetail('c12','8')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft12.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft12.1')">test_poznavacky_okruzni_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft12.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft12.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft12.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\poznavacky.py", line 57, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft12.2" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft12.2')">test_poznavacky_vikendy_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft12.2')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft12.2' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft12.2').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\poznavacky.py", line 57, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft12.3" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft12.3')">test_poznavacky_rodiny_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft12.3')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft12.3' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft12.3').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\poznavacky.py", line 57, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft12.4" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft12.4')">test_poznavacky_zazitky_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft12.4')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft12.4' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft12.4').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\poznavacky.py", line 57, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft12.5" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft12.5')">test_poznavacky_okruzni_C</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft12.5')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft12.5' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft12.5').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\poznavacky.py", line 57, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft12.6" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft12.6')">test_poznavacky_vikendy_C</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft12.6')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft12.6' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft12.6').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\poznavacky.py", line 57, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft12.7" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft12.7')">test_poznavacky_rodiny_C</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft12.7')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft12.7' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft12.7').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\poznavacky.py", line 57, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft12.8" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft12.8')">test_poznavacky_zazitky_C</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft12.8')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft12.8' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft12.8').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\poznavacky.py", line 57, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c13','2')">FW_Automation_Local_Deploy_PyCharm.SDO_C.TestSDO_C</a></td>
            <td>2</td>
            <td>0</td>
            <td>0</td>
            <td>2</td>
            <td>
                <button><a href="javascript:showClassDetail('c13','2')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft13.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft13.1')">test_SDO_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft13.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft13.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft13.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SDO_C.py", line 10, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft13.2" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft13.2')">test_SDO_zlutak_to_SRL_R</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft13.2')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft13.2' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft13.2').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SDO_C.py", line 10, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c14','5')">FW_Automation_Local_Deploy_PyCharm.SRL_C.Test_SRL_C</a></td>
            <td>5</td>
            <td>0</td>
            <td>0</td>
            <td>5</td>
            <td>
                <button><a href="javascript:showClassDetail('c14','5')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft14.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft14.1')">test_SRL_sort_cheapest</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft14.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft14.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft14.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SRL_C.py", line 21, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft14.2" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft14.2')">test_SRL_sort_expensive</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft14.2')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft14.2' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft14.2').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SRL_C.py", line 21, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft14.3" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft14.3')">test_SRL_map</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft14.3')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft14.3' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft14.3').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SRL_C.py", line 21, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft14.4" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft14.4')">test_SRL_filtr_strava</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft14.4')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft14.4' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft14.4').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SRL_C.py", line 21, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft14.5" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft14.5')">test_srl_C</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft14.5')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft14.5' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft14.5').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SRL_C.py", line 21, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c15','1')">FW_Automation_Local_Deploy_PyCharm.SRL_D.TestSRL_D</a></td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>1</td>
            <td>
                <button><a href="javascript:showClassDetail('c15','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft15.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft15.1')">test_SRL_D</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft15.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft15.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft15.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SRL_D.py", line 124, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c16','6')">FW_Automation_Local_Deploy_PyCharm.HP_C.Test_HP_C</a></td>
            <td>6</td>
            <td>0</td>
            <td>0</td>
            <td>6</td>
            <td>
                <button><a href="javascript:showClassDetail('c16','6')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft16.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft16.1')">test_HP_slider_click_detail_hotelu</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft16.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft16.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft16.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\HP_C.py", line 75, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft16.2" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft16.2')">test_HP_bannery_check</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft16.2')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft16.2' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft16.2').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\HP_C.py", line 75, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft16.3" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft16.3')">test_HP_zlutak_to_SRL_pobyt</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft16.3')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft16.3' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft16.3').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\HP_C.py", line 75, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft16.4" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft16.4')">test_HP_zlutak_to_SRL_poznavacky</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft16.4')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft16.4' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft16.4').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\HP_C.py", line 75, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft16.5" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft16.5')">test_HP_zlutak_to_groupsearch_pobyt</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft16.5')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft16.5' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft16.5').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\HP_C.py", line 75, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
            <tr id="ft16.6" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft16.6')">test_HP_zlutak_to_groupsearch_poznavacky</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft16.6')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft16.6' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft16.6').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\HP_C.py", line 75, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        
        <tr class='errorClass' style="font-weight:bold;color:white;">
            <td><a href="javascript:showClassDetail('c17','1')">FW_Automation_Local_Deploy_PyCharm.SRL_results_comparer.Test_SRL_C_comparer</a></td>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>1</td>
            <td>
                <button><a href="javascript:showClassDetail('c17','1')"
                           style="color:#660066;">Detail</a></button>
            </td>
        </tr>
            
            <tr id="ft17.1" class='none'>
                <td class='errorCase'>
                    <div class='testcase'>
                        <a class="popup_link" onfocus='this.blur();'
                           href="javascript:showTestDetail('div_ft17.1')">test_SRL_number_of_results_comparer</a>
                    </div>
                </td>
                <td colspan='5' align='center'>
                    <div>
                        <!--css div popup start-->
                        <button>
                            <a class="popup_link" onfocus='this.blur();'
                               href="javascript:showTestDetail('div_ft17.1')" style="color:#660066;">
                                ERROR
                            </a></button>
                        <div id='div_ft17.1' class="popup_window">
                            <div style='text-align: right; color:red;cursor:pointer'>
                                <a onfocus='this.blur();'
                                   onclick="document.getElementById('div_ft17.1').style.display = 'none'; "
                                   style="color:red;">
                                    [x]</a>
                            </div>
                            <pre></pre>
                            <pre style="color: red;">Traceback (most recent call last):
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 65, in __extract_zip
    archive.extractall(to_directory)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\KADOUN\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\SRL_results_comparer.py", line 56, in setUp
    setUp(self)
  File "C:\Users\KADOUN\Desktop\Automatization_Project_Master_QA\FW_Automation_Local_Deploy_PyCharm\to_import.py", line 28, in setUp
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "C:\Users\KADOUN\AppData\Roaming\Python\Python38\site-packages\webdriver_manager\core\file_manager.py", line 81, in __extract_zip
    os.replace(source, destination)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver-win32\\chromedriver.exe' -> 'C:\\Users\\KADOUN\\.wdm\\drivers\\chromedriver\\win64\\116.0.5845.188\\chromedriver.exe'
</pre>
                        </div>
                        <!--css div popup end-->
                    </div>
                </td>
            </tr>
            
        

        <tr id='total_row'>
            <td>Total</td>
            <td>40</td>
            <td>2</td>
            <td>0</td>
            <td>38</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</div>
<br><br>
<div id='ending'><b>Time Elapsed: </b>0:02:43.335956</div>
</body>
</html>